version: "3"

services:
  bombardier:
    image: pashaman/rsfo
    env_file:
      - .env
    restart: unless-stopped
  bombardieracf:
    image: pashaman/rsfocf
    env_file:
      - .env
    restart: unless-stopped



